# Generated by Django 2.1.7 on 2019-03-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190329_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='append_author', to='blog.Author')),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='append_book', to='blog.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
