# Generated by Django 2.1.7 on 2019-04-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book2author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book2author',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book2Author',
        ),
    ]
