# Generated by Django 2.1.7 on 2019-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190424_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='brief',
            field=models.CharField(default='京', max_length=32),
        ),
    ]
