# Generated by Django 2.1.7 on 2019-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_province_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='brief',
            field=models.CharField(default='', max_length=32),
        ),
    ]
